[package]
name = "thegrep"
version = "1.0.0"
authors = ["Madison Huber <hubermm@live.unc.edu>", "Alana Fiordalisi <fiordali@live.unc.edu>"]
edition = "2018"

[dependencies]
structopt = "0.2"
rand = "0.6"
